### PR TITLE
Resolve #63 by updating function install

### LINKED ISSUE #63: conn_file instructions
I think I found two problems with the instructions this package provides for users in terms of their conn_file.

1) The man page recommends comma-separated values, but [an error message about the same thing](https://github.com/ropensci/ecoretriever/blob/4efb4812a8cac18ce86f381d498627b59434ed10/R/ecoretriever.R#L34-L37) recommends space-delimited.

2) Users might take `port 1111` literally. A more obvious placeholder such as `portnumber` might be better.

### PR DESCRIPTION
**Pull request by dmcglinn**
The format of the connection file which stores the parameters of the database connection was changed from a two column space separated file to a two row comma separated value. This change was made because the documentation was inconsistent with the use case and the csv format is easier to describe and is likely to be more familiar to users.

### CODE REVIEW

**Comment by ethanwhite** [comment]
@dmcglinn - can you remind me about the background a little more. Is this something specific to `ecoretriever` or is it using the configuration file that the `retriever` generates and/or reads?

**Comment by dmcglinn** [comment]
This is specific to the `ecoretriever`. It passes those arguments to the `retriever` 

https://github.com/dmcglinn/ecoretriever/blob/conn/R/ecoretriever.R#L43-L45

because the `retriever` function `install` requires those arguments for mysql & postgres connections

**Comment by ethanwhite** [comment]
OK thanks. Two follow up questions:

1. Does this break the existing functionality if anyone is using it? If so, can we make the change in such a way that the code can continue to read the legacy files just in case?
2. This seems to duplicate the functionality of the `retriever`'s `connections.config` file, which is structured like:

```
PostgreSQL,{'database': 'postgres', 'database_name': '{db}', 'host': 'localhost', 'table_name': '{db}.{table}', 'user': 'username', 'password': 'mypassword', 'port': '5432'}
MySQL,{'database_name': '{db}', 'host': 'localhost', 'table_name': '{db}.{table}', 'user': 'root', 'password': 'mypassword', 'port': '3306'}
```

So it might be worth thinking about making these consistent either now or in the future.

**Comment by dmcglinn** [comment]
Thanks for the info. So if the `retriever` function `install` is not supplied those parameters in the call it looks to the file `connections.config`. Where does that file need to be located. I'm going to add documentation on that.  Also it should be possible to allow the legacy format to work. In the future maybe we should only support the `retriever`'s `connections.config` rather than having redundancy built in.

**Comment by ethanwhite** [comment]
> So if the retriever function install is not supplied those parameters in the call it looks to the file connections.config. Where does that file need to be located.

At the moment that file is only used by the GUI, so it can't be used directly by `ecoretriever` at the moment. We have an open issue for using DBMS specific credential files https://github.com/weecology/retriever/issues/421, but I think it would be good to implement a general version of the kind of solution `ecoretriever` and the GUI have separately.

So, having thought about this I guess I'm fine with going forward with your current approach, but would like it to be backwards compatible for the moment until we sort out a general solution. Does changing the documentation but not the actual structure of the file sound OK to you?

**Comment by dmcglinn** [comment]
Yea that sounds like the simplest solution.  I'll implement that.

**Comment by dmcglinn** [comment]
It seems like the simplest way to accomplish this is to swash this PR and start a new one.

**Pull request closed without merging**
