### PR TITLE
Rename to `Data Retriever` and `dataretriever`

### LINKED ISSUE #71: Rebrand to match Data Retriever
We've now rebranded the EcoData Retriever to just the Data Retriever. We should mirror that here both in the docs and by changing the package name, probably to `dataretriever` (since there was resistance in the past to using `retriever` which is the Python package name.

### PR DESCRIPTION
**Pull request by ethanwhite**
Now that the core retriever is expanding beyond ecological data it no longer makes sense to have
this package named the `ecoretriever`. This implements a package wide shift to `dataretriever` and `Data Retriever`, including name changes and updating links to the new [Data Retriever](http://data-retriever.org) domain.

Once these are in we'll probably want to rename the repo as well.

We'll also need to keep this in mind for the next CRAN submission in case there are any complexities there.

Closes #71.

### CODE REVIEW

**Comment by sckott** [comment]
there's a thread here http://r.789695.n4.nabble.com/Rename-the-package-published-on-CRAN-td4674670.html (Uwe is one of the cran maintainers) - I'd email cran maintainers and ask - it may be that the easiest thing is to just submit as a completely new package, and just ask them to archive the old one, or just leave it up if you want

**Comment by ethanwhite** [comment]
Thanks @sckott!

**Comment by henrykironde** [comment]
@ethanwhite could you rebase this PR

**Comment by dmcglinn** [comment]
Thanks @ethanwhite and @sckott for these suggestions. This sounds good to me. I'll make the change to the repo's name once this PR is merged.

**Comment by ethanwhite** [comment]
Sorry for the delay. Travel.

I'm working on the rebase now and wondering whether or not we should use `rdataretriever` instead of `dataretriever` to avoid confusion with the core product. It also makes the R wrapper identity of the package more explicit. Thoughts?

**Comment by dmcglinn** [comment]
I like `rdataretriever`

**Comment by ethanwhite** [comment]
Rebased and name changes made in #91 which supercedes this.

**Pull request closed without merging**
