### PR TITLE
Add reset to ecoretriever

### LINKED ISSUE #69: Add wrapper for reset
The core retriever allows users to reset cached scripts, raw data, and config files using

```
retriever reset all
retriever reset scripts
retriever reset data
retriever reset connections
```

This is handy for making sure everything is up-to-date, testing, and fixing broken installs.

### PR DESCRIPTION
**Pull request by henrykironde**
Ecoretriever does reset non dependent on the retriever
Hence ecoretriever directly removes the requested paths.
fixes #69

### CODE REVIEW

**Comment by ethanwhite** [comment]
LGTM. Won't merge for a bit in case @dmcglinn wants to take a look.

**Comment by dmcglinn** [comment]
Hmm on my windows machine I see the following behavior. Scripts and raw data are downloaded into `C:/Users/Daniel/Documents/.retriever` but the R code `dirname(Sys.getenv('HOME'))` which is used to identify which files to unlink is returning `C:/Users/Daniel`. So in other words there is a mismatch as to where the retriever files are being stored and where the new `reset` function thinks they should be stored. Also is there a reason why the unlinking method is being used instead of directly issuing the command `retriever reset all` via the R function `run_cli`?

**Comment by ethanwhite** [comment]
@dmcglinn is that in RStudio? If so then it looks like this mismatch is the writing issue in #81. I have no idea why It's writing into `Documents` in RStudio on Windows.

**Comment by henrykironde** [comment]
I have tried to find the problem but it seems that is a `windows + Rstudio + environmental path variables problem`.
Run `Sys.getenv() in Rstudio`, notice that the home path is different from your expected path.
Try setting the HOME path in the Environmental variables

**Comment by henrykironde** [comment]
Additionally you may need to change some permissions or run `Rstudio` as admin

**Comment by ethanwhite** [comment]
Not in this PR, but could we check the output of `Sys.getenv('HOME')` when setting the working directory and if it contains `'/Documents'` then strip it off?

**Comment by ethanwhite** [comment]
@dmcglinn My vote would be to go ahead and merge this since the problem isn't with this PR and the new functionality is still a bonus on all but particular system type.

**Comment by dmcglinn** [comment]
Sounds good. Let's merge but I think by merging the other PR's I introduced some conflicts to this PR.

**Comment by ethanwhite** [comment]
> Sounds good. Let's merge but I think by merging the other PR's I introduced some conflicts to this PR.

Good news is that we fixed this this morning in https://github.com/ropensci/ecoretriever/pull/90/commits/dde9fe93312b485050517ee1076131dc3243299f 🎉

@henrykironde if you can rebase this we should be able to get it in.

**Comment by henrykironde** [comment]
Closing, The changes have been put in a new PR  #93

**Pull request closed without merging**
